//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:60557/API.
        /// </summary>
        internal static string DebugAPI {
            get {
                return ResourceManager.GetString("DebugAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query := Values+ ;
        ///Values = grammar | metadata | view ;
        ///grammar := &apos;grammar[&lt;[&apos; + string + &apos;,&apos; + data + &apos;]&gt;]&apos; ;
        ///metadata := &apos;metadata[&lt;[&apos; + name + &apos;,&apos; + data + &apos;]&gt;]&apos; ;
        ///view :=&apos;view[&lt;[&apos; + name + &apos;,&apos; + data + &apos;]&gt;]&apos; ;
        ///data    = &apos;data{{&apos; + subtype + &apos;}}&apos; ;
        ///subtype = Columns | Rows | Data ;
        ///Columns := &apos;Columns(&apos; + interests + &apos;)&apos; ;
        ///Rows := &apos;Rows(&apos; + interests + &apos;)&apos; ;
        ///Data -:= &apos;Data(&apos; + interests + &apos;)&apos; ;
        ///interests = interest+ ;
        ///interest  = value | escapes ;
        ///escapes   -= &apos;|&apos; ;
        ///name    -:= string ;
        ///va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReaderAPI {
            get {
                return ResourceManager.GetString("ReaderAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to net.tcp://POL-AD-D01731:60557/excel.
        /// </summary>
        internal static string RealtimeAPI {
            get {
                return ResourceManager.GetString("RealtimeAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://POL-AD-D03516/API.
        /// </summary>
        internal static string ReleaseAPI {
            get {
                return ResourceManager.GetString("ReleaseAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;customUI xmlns=&apos;http://schemas.microsoft.com/office/2009/07/customui&apos; onLoad=&apos;rLoad&apos;&gt;
        ///	                &lt;ribbon&gt;
        ///		                &lt;tabs&gt;
        ///			                &lt;tab id=&apos;Tracker&apos; label=&apos;ND Tracker&apos; insertBeforeMso=&apos;TabHome&apos;&gt;
        ///				                &lt;group id=&apos;trackerGroup&apos; label=&apos;Trackers and Views&apos;&gt;
        ///					                &lt;dropDown id=&apos;Area&apos; onAction=&apos;rAction&apos; getItemCount=&apos;rCount&apos; label=&apos;Items&apos; getItemLabel=&apos;rItemLabel&apos; getSelectedItemIndex=&apos;rSelected&apos; getVisible=&apos;rVisible&apos; sizeString=&apos;iWWWWWWWWWWWWWWWWWWWW&apos; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
    }
}
